apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-web-app-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: house-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: house-web-app
    spec:
      containers:
        - image: house-web-app:0.2.2
          imagePullPolicy: Never
          name: house-web-app-container
          ports:
            - containerPort: 80
