apiVersion: v1
kind: Service
metadata:
  name: house-web-app-nodeport
spec:
  selector:
    app: house-web-app
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (e.g., standard HTTP port)
      targetPort: 3000 # The port your React app listens on inside the container
  type: NodePort # This exposes the service on a static port on the Minikube node