apiVersion: v1
kind: Service
metadata:
  name: web-app-to-scraper-api-svc
spec:
  selector:
    app: scraper-api  # Replace with the labels of your target Pods
  ports:
    - protocol: TCP
      port: 83        # The port the Service will listen on
      targetPort: 5000  # The port your target Pod's container is listening on
  type: ClusterIP